require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

def shared_pods
  # pods list here
  # ......
  # ......
end


target 'ReactNativeStrucure' do
shared_pods
    
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'ReactNativeStrucureTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
  
end


target 'ReactNativeStrucureDev' do
shared_pods
  # Comment the next line if you don't want to use dynamic frameworks
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  # Pods for ReactNativeStrucureDev

end

target 'ReactNativeStrucureStage' do
shared_pods
  # Comment the next line if you don't want to use dynamic frameworks
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  # Pods for ReactNativeStrucureStage

end
